version: "3.8"

volumes:
    api_node_modules:
        driver: local
    ui_node_modules:
        driver: local

services:
    ui:
        image: node:18-bullseye
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
        volumes:
            - ./ui:/srv/ui:delegated
            - .git:/srv/ui/.git:delegated
            - ui_node_modules:/srv/ui/node_modules:delegated
        working_dir: /srv/ui
        command: [ "npm", "run", "develop" ]

    edge:
        image: nginx:latest
        hostname: edge
        tty: true
        environment:
            TERM: "xterm-256color"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./scripts/wait-for-it.sh:/wait-for-it.sh
        command:
            [
                "/wait-for-it.sh",
                "app:8080",
                "-t",
                "10",
                "--",
                "nginx",
                "-g",
                "daemon off;"
            ]
        ports:
            - 9000:9000
